
import { Client, AccountId, PrivateKey, ContractCreateFlow, ContractFunctionParameters } from "@hashgraph/sdk";
import * as fs from 'fs';
import * as path from 'path';
import { VulnerableBoxArtifact } from '../src/components/hunt/contracts/VulnerableBox';
import { PausableBoxArtifact } from '../src/components/hunt/contracts/PausableBox';

// Define paths for output
const PLAYGROUND_TARGETS_PATH = path.resolve(__dirname, '../src/data/targets.json');
const AGENT_TARGETS_PATH = path.resolve(__dirname, '../../nullshot-agent/src/data/targets.json');

// Configuration
const ACCOUNT_ID = "0.0.7160195";
const PRIVATE_KEY = "0xc60bce878f9308a8a80f9b71bb3d4e69af0a5d958c676817238544a8b96715cc";

// Map names to mock vulnerability types and contract type
const CONTRACTS = [
    { name: "Bank_Reentrancy", type: "Reentrancy", file: "Bank_Reentrancy.sol", action: "upgrade" },
    { name: "Token_Overflow", type: "Integer Overflow", file: "Token_Overflow.sol", action: "upgrade" },
    { name: "Admin_Access", type: "Access Control", file: "Admin_Access.sol", action: "upgrade" },
    { name: "Logic_Unchecked", type: "Unchecked Call", file: "Logic_Unchecked.sol", action: "upgrade" },
    { name: "Data_Visibility", type: "Private Data Exposure", file: "Data_Visibility.sol", action: "pause" } // Non-upgradeable
];

async function deploy() {
    console.log(`Starting deployment to Hedera Testnet...`);
    console.log(`Operator: ${ACCOUNT_ID}`);

    if (!PRIVATE_KEY) {
        throw new Error("Private Key missing");
    }

    const client = Client.forTestnet();

    let operatorKey;
    try {
        if (PRIVATE_KEY.startsWith("0x")) {
            operatorKey = PrivateKey.fromStringECDSA(PRIVATE_KEY);
        } else {
            operatorKey = PrivateKey.fromString(PRIVATE_KEY);
        }
    } catch (e) {
        console.log("Standard parsing failed, trying DER...");
        operatorKey = PrivateKey.fromStringDer(PRIVATE_KEY);
    }

    client.setOperator(AccountId.fromString(ACCOUNT_ID), operatorKey);

    const results = [];

    for (const contract of CONTRACTS) {
        console.log(`Deploying ${contract.name}...`);

        try {
            // Select bytecode based on action
            let bytecode;
            if (contract.action === "upgrade") {
                bytecode = VulnerableBoxArtifact.bytecode;
            } else {
                bytecode = PausableBoxArtifact.bytecode;
            }

            // Remove 0x prefix for Hedera SDK if present
            if (bytecode.startsWith("0x")) {
                bytecode = bytecode.substring(2);
            }

            const transaction = new ContractCreateFlow()
                .setBytecode(bytecode)
                .setGas(1_500_000); // Increased gas for safety

            const txResponse = await transaction.execute(client);
            const receipt = await txResponse.getReceipt(client);
            const contractId = receipt.contractId;
            const solidityAddress = contractId?.toSolidityAddress();

            console.log(` - Deployed ${contract.name} at ${contractId} (EVM: 0x${solidityAddress})`);

            results.push({
                name: contract.name,
                contractId: contractId?.toString(),
                address: `0x${solidityAddress}`,
                vulnerability: contract.type,
                filename: contract.file,
                action: contract.action
            });

        } catch (error) {
            console.error(`Failed to deploy ${contract.name}:`, error);
        }
    }

    // Output JSON
    const output = {
        timestamp: new Date().toISOString(),
        network: "Hedera Testnet",
        contracts: results
    };

    const jsonContent = JSON.stringify(output, null, 2);

    // Ensure directories exist
    fs.mkdirSync(path.dirname(PLAYGROUND_TARGETS_PATH), { recursive: true });
    fs.mkdirSync(path.dirname(AGENT_TARGETS_PATH), { recursive: true });

    // Write files
    fs.writeFileSync(PLAYGROUND_TARGETS_PATH, jsonContent);
    console.log(`Wrote targets to ${PLAYGROUND_TARGETS_PATH}`);

    fs.writeFileSync(AGENT_TARGETS_PATH, jsonContent);
    console.log(`Wrote targets to ${AGENT_TARGETS_PATH}`);

    // Update targets.ts for Frontend Build Stability (ensure it matches the JSON)
    const tsPath = path.resolve(__dirname, '../src/data/targets.ts');
    const tsContent = `// This file is auto-generated by the deployment script
export const targetsData = ${jsonContent} as const;

export default targetsData;
`;
    fs.writeFileSync(tsPath, tsContent);
    console.log(`Updated frontend source: ${tsPath}`);

    process.exit(0);
}

deploy().catch((err) => {
    console.error(err);
    process.exit(1);
});
