// This file is auto-generated by the deployment script or populated with default demo data
export const targetsData = {
  "timestamp": "2025-12-06T14:46:48.422Z",
  "network": "Hedera Testnet",
  "contracts": [
    {
      "name": "Bank_Reentrancy",
      "contractId": "0.0.7379380",
      "address": "0x00000000000000000000000000000000007099b4",
      "vulnerability": "Reentrancy",
      "filename": "Bank_Reentrancy.sol"
    },
    {
      "name": "Token_Overflow",
      "contractId": "0.0.7379382",
      "address": "0x00000000000000000000000000000000007099b6",
      "vulnerability": "Integer Overflow",
      "filename": "Token_Overflow.sol"
    },
    {
      "name": "Admin_Access",
      "contractId": "0.0.7379384",
      "address": "0x00000000000000000000000000000000007099b8",
      "vulnerability": "Access Control",
      "filename": "Admin_Access.sol"
    },
    {
      "name": "Logic_Unchecked",
      "contractId": "0.0.7379388",
      "address": "0x00000000000000000000000000000000007099bc",
      "vulnerability": "Unchecked Call",
      "filename": "Logic_Unchecked.sol"
    },
    {
      "name": "Data_Visibility",
      "contractId": "0.0.7379393",
      "address": "0x00000000000000000000000000000000007099c1",
      "vulnerability": "Private Data Exposure",
      "filename": "Data_Visibility.sol"
    }
  ]
} as const;

export default targetsData;
