// This file is auto-generated by the deployment script
export const targetsData = {
  "timestamp": "2025-12-09T10:29:16.616Z",
  "network": "Hedera Testnet",
  "contracts": [
    {
      "name": "Bank_Reentrancy",
      "contractId": "0.0.7407462",
      "address": "0x0000000000000000000000000000000000710766",
      "vulnerability": "Reentrancy",
      "filename": "Bank_Reentrancy.sol",
      "action": "upgrade"
    },
    {
      "name": "Token_Overflow",
      "contractId": "0.0.7407464",
      "address": "0x0000000000000000000000000000000000710768",
      "vulnerability": "Integer Overflow",
      "filename": "Token_Overflow.sol",
      "action": "upgrade"
    },
    {
      "name": "Admin_Access",
      "contractId": "0.0.7407466",
      "address": "0x000000000000000000000000000000000071076a",
      "vulnerability": "Access Control",
      "filename": "Admin_Access.sol",
      "action": "upgrade"
    },
    {
      "name": "Logic_Unchecked",
      "contractId": "0.0.7407468",
      "address": "0x000000000000000000000000000000000071076c",
      "vulnerability": "Unchecked Call",
      "filename": "Logic_Unchecked.sol",
      "action": "upgrade"
    },
    {
      "name": "Data_Visibility",
      "contractId": "0.0.7407472",
      "address": "0x0000000000000000000000000000000000710770",
      "vulnerability": "Private Data Exposure",
      "filename": "Data_Visibility.sol",
      "action": "pause"
    }
  ]
} as const;

export default targetsData;
