// This is a minimal artifact for a vulnerable contract that allows upgrading.
// In a real scenario, this would be generated by hardhat/foundry.

export const VulnerableBoxArtifact = {
  abi: [
    {
      "inputs": [],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "implementation",
          "type": "address"
        }
      ],
      "name": "Upgraded",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "deposit",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "newImplementation",
          "type": "address"
        }
      ],
      "name": "upgradeTo",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "stateMutability": "payable",
      "type": "receive"
    }
  ] as const,
  bytecode: "0x608060405234801561001057600080fd5b50610150806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063365b98b21461003b578063d09de08a14610045575b61004361003e3660046100d2565b005b005b6100436100d0565b61005860048036038101906100539190610103565b61005a565b005b60005473ffffffffffffffffffffffffffffffffffffffff16331461008057600080fd5b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055507fbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b806040516100c69190610129565b60405180910390a150565b005b565b005b600080fd5b6000819050919050565b6101008111156100f257600080fd5b50565b6000819050919050565b61011d816100e4565b811461012857600080fd5b50565b600081905092915050565b61013c816100fd565b82525050565b60006020820190506101576000830184610133565b9291505056fea2646970667358221220a2e432c02113334516738910452311223344556677889900aabbccddeeff001164736f6c63430008000033"
};
